#!/usr/bin/env bun
// @generated by mcporter@0.0.0 on 2026-03-02T20:00:43.552Z. DO NOT EDIT.
import { Command } from 'commander';
import { createRuntime, createServerProxy } from 'mcporter';
import { createCallResult } from 'mcporter';

const embeddedServer = {
  "name": "smartbear",
  "description": "mcphub_smartbear_group",
  "command": {
    "kind": "http",
    "url": "http://localhost:9700/mcp/smartbear",
    "headers": {
      "accept": "application/json, text/event-stream"
    }
  },
  "source": {
    "kind": "import",
    "path": "/home/danil/.codex/config.toml",
    "importKind": "codex"
  },
  "sources": [
    {
      "kind": "import",
      "path": "/home/danil/.codex/config.toml",
      "importKind": "codex"
    }
  ]
} as const;
const embeddedSchemas = {
  "smartbear-list_organizations": {
    "type": "object",
    "properties": {},
    "required": []
  },
  "smartbear-list_projects": {
    "type": "object",
    "properties": {
      "organization_id": {
        "type": "string",
        "description": "Bugsnag organization ID"
      }
    },
    "required": [
      "organization_id"
    ]
  },
  "smartbear-list_errors": {
    "type": "object",
    "properties": {
      "project_id": {
        "type": "string",
        "description": "Bugsnag project ID"
      },
      "status": {
        "type": "string",
        "enum": [
          "open",
          "fixed",
          "ignored"
        ],
        "description": "Filter by error status"
      },
      "sort": {
        "type": "string",
        "enum": [
          "newest",
          "oldest",
          "priority"
        ],
        "description": "Sort order for errors"
      },
      "limit": {
        "type": "number",
        "description": "Maximum number of errors to return"
      }
    },
    "required": [
      "project_id"
    ]
  },
  "smartbear-view_error": {
    "type": "object",
    "properties": {
      "error_id": {
        "type": "string",
        "description": "Bugsnag error ID"
      }
    },
    "required": [
      "error_id"
    ]
  },
  "smartbear-list_error_events": {
    "type": "object",
    "properties": {
      "project_id": {
        "type": "string",
        "description": "Bugsnag project ID"
      },
      "error_id": {
        "type": "string",
        "description": "Bugsnag error ID"
      },
      "limit": {
        "type": "number",
        "description": "Maximum number of events to return"
      }
    },
    "required": [
      "project_id",
      "error_id"
    ]
  },
  "smartbear-view_latest_event": {
    "type": "object",
    "properties": {
      "error_id": {
        "type": "string",
        "description": "Bugsnag error ID"
      }
    },
    "required": [
      "error_id"
    ]
  },
  "smartbear-view_event": {
    "type": "object",
    "properties": {
      "project_id": {
        "type": "string",
        "description": "Bugsnag project ID"
      },
      "event_id": {
        "type": "string",
        "description": "Bugsnag event ID"
      }
    },
    "required": [
      "project_id",
      "event_id"
    ]
  },
  "smartbear-view_stacktrace": {
    "type": "object",
    "properties": {
      "project_id": {
        "type": "string",
        "description": "Bugsnag project ID"
      },
      "event_id": {
        "type": "string",
        "description": "Bugsnag event ID"
      },
      "include_code": {
        "type": "boolean",
        "description": "Include source code context if available"
      }
    },
    "required": [
      "project_id",
      "event_id"
    ]
  },
  "smartbear-view_exception_chain": {
    "type": "object",
    "properties": {
      "project_id": {
        "type": "string",
        "description": "Bugsnag project ID"
      },
      "event_id": {
        "type": "string",
        "description": "Bugsnag event ID"
      }
    },
    "required": [
      "project_id",
      "event_id"
    ]
  },
  "smartbear-search_issues": {
    "type": "object",
    "properties": {
      "project_id": {
        "type": "string",
        "description": "Bugsnag project ID"
      },
      "query": {
        "type": "string",
        "description": "Search query"
      },
      "error_class": {
        "type": "string",
        "description": "Filter by error class"
      },
      "app_version": {
        "type": "string",
        "description": "Filter by app version"
      }
    },
    "required": [
      "project_id"
    ]
  },
  "smartbear-view_tabs": {
    "type": "object",
    "properties": {
      "project_id": {
        "type": "string",
        "description": "Bugsnag project ID"
      },
      "event_id": {
        "type": "string",
        "description": "Bugsnag event ID"
      },
      "include_code": {
        "type": "boolean",
        "description": "Include source code context in stacktrace if available"
      }
    },
    "required": [
      "project_id",
      "event_id"
    ]
  }
} as const;
const embeddedName = "smartbear";
const embeddedDescription = "mcphub_smartbear_group";
const generatorInfo = "Generated by mcporter@0.0.0 — https://github.com/steipete/mcporter";
const generatorTools = [
  {
    "name": "smartbear-list-organizations",
    "description": "List available Bugsnag organizations",
    "usage": "smartbear-list-organizations [--raw <json>]",
    "flags": "[--raw <json>]"
  },
  {
    "name": "smartbear-list-projects",
    "description": "List projects in an organization",
    "usage": "smartbear-list-projects --organization-id <organization-id> [--raw <json>]",
    "flags": "--organization-id <organization-id> [--raw <json>]"
  },
  {
    "name": "smartbear-list-errors",
    "description": "List errors in a project with filtering options",
    "usage": "smartbear-list-errors --project-id <project-id> [--status <status:open|fixed|ignored>] [--sort <sort:newest|oldest|priority>] [--limit <limit:number>] [--raw <json>]",
    "flags": "--project-id <project-id> [--status <status:open|fixed|ignored>] [--sort <sort:newest|oldest|priority>] [--limit <limit:number>] [--raw <json>]"
  },
  {
    "name": "smartbear-view-error",
    "description": "Get detailed information about a specific error",
    "usage": "smartbear-view-error --error-id <error-id> [--raw <json>]",
    "flags": "--error-id <error-id> [--raw <json>]"
  },
  {
    "name": "smartbear-list-error-events",
    "description": "List events (occurrences) for a specific error",
    "usage": "smartbear-list-error-events --project-id <project-id> --error-id <error-id> [--limit <limit:number>] [--raw <json>]",
    "flags": "--project-id <project-id> --error-id <error-id> [--limit <limit:number>] [--raw <json>]"
  },
  {
    "name": "smartbear-view-latest-event",
    "description": "View the latest event for an error",
    "usage": "smartbear-view-latest-event --error-id <error-id> [--raw <json>]",
    "flags": "--error-id <error-id> [--raw <json>]"
  },
  {
    "name": "smartbear-view-event",
    "description": "View detailed information about a specific event",
    "usage": "smartbear-view-event --project-id <project-id> --event-id <event-id> [--raw <json>]",
    "flags": "--project-id <project-id> --event-id <event-id> [--raw <json>]"
  },
  {
    "name": "smartbear-view-stacktrace",
    "description": "Extract and format stacktrace information from an event",
    "usage": "smartbear-view-stacktrace --project-id <project-id> --event-id <event-id> [--include-code <include-code:true|false>] [--raw <json>]",
    "flags": "--project-id <project-id> --event-id <event-id> [--include-code <include-code:true|false>] [--raw <json>]"
  },
  {
    "name": "smartbear-view-exception-chain",
    "description": "View the full chain of exceptions for an event",
    "usage": "smartbear-view-exception-chain --project-id <project-id> --event-id <event-id> [--raw <json>]",
    "flags": "--project-id <project-id> --event-id <event-id> [--raw <json>]"
  },
  {
    "name": "smartbear-search-issues",
    "description": "Search for issues using various criteria",
    "usage": "smartbear-search-issues --project-id <project-id> [--query <query>] [--error-class <error-class>] [--app-version <app-version>] [--raw <json>]",
    "flags": "--project-id <project-id> [--query <query>] [--error-class <error-class>] [--app-version <app-version>] [--raw <json>]"
  },
  {
    "name": "smartbear-view-tabs",
    "description": "View all event data tabs including app, device, user, request, breadcrumbs, metadata, and stacktrace",
    "usage": "smartbear-view-tabs --project-id <project-id> --event-id <event-id> [--include-code <include-code:true|false>] [--raw <json>]",
    "flags": "--project-id <project-id> --event-id <event-id> [--include-code <include-code:true|false>] [--raw <json>]"
  }
] as const;
const embeddedMetadata = {
  "schemaVersion": 1,
  "generatedAt": "2026-03-02T20:00:43.552Z",
  "generator": {
    "name": "mcporter",
    "version": "0.0.0"
  },
  "server": {
    "name": "smartbear",
    "source": {
      "kind": "import",
      "path": "/home/danil/.codex/config.toml",
      "importKind": "codex"
    },
    "definition": {
      "name": "smartbear",
      "description": "mcphub_smartbear_group",
      "command": {
        "kind": "http",
        "url": "http://localhost:9700/mcp/smartbear",
        "headers": {
          "accept": "application/json, text/event-stream"
        }
      }
    }
  },
  "artifact": {
    "path": "",
    "kind": "template"
  },
  "invocation": {
    "serverRef": "smartbear",
    "runtime": "bun",
    "bundler": "bun",
    "timeoutMs": 60000,
    "minify": false
  }
} as const;
const artifactKind = determineArtifactKind();
const program = new Command();
program.name(embeddedName);
program.description(embeddedDescription);
program.option('-t, --timeout <ms>', 'Call timeout in milliseconds', (value) => parseInt(value, 10), 60000);
program.option('-o, --output <format>', 'Output format: text|markdown|json|raw', 'text');
const commandSignatures: Record<string, string> = {
  "smartbear-list-organizations": "function smartbear-list_organizations();",
  "smartbear-list-projects": "function smartbear-list_projects(organization_id: string);",
  "smartbear-list-errors": "function smartbear-list_errors(project_id: string, status?: \"open\" | \"fixed\" | \"ignored\", sort?: \"newest\" | \"oldest\" | \"priority\", limit?: number);",
  "smartbear-view-error": "function smartbear-view_error(error_id: string);",
  "smartbear-list-error-events": "function smartbear-list_error_events(project_id: string, error_id: string, limit?: number);",
  "smartbear-view-latest-event": "function smartbear-view_latest_event(error_id: string);",
  "smartbear-view-event": "function smartbear-view_event(project_id: string, event_id: string);",
  "smartbear-view-stacktrace": "function smartbear-view_stacktrace(project_id: string, event_id: string, include_code?: boolean);",
  "smartbear-view-exception-chain": "function smartbear-view_exception_chain(project_id: string, event_id: string);",
  "smartbear-search-issues": "function smartbear-search_issues(project_id: string, query?: string, error_class?: string, app_version?: string);",
  "smartbear-view-tabs": "function smartbear-view_tabs(project_id: string, event_id: string, include_code?: boolean);"
};
program.configureHelp({
	commandTerm(cmd) {
		const term = cmd.name();
		return commandSignatures[term] ?? cmd.name();
	},
});
program.showSuggestionAfterError(true);

program
	.command("smartbear-list-organizations")
	.summary("smartbear-list-organizations [--raw <json>]")
	.description("List available Bugsnag organizations")
	.usage("[--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	
	.alias("smartbear-list_organizations")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			
			const call = (proxy.smartbearListOrganizations as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 60000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call smartbear.smartbear-list_organizations()");

program
	.command("smartbear-list-projects")
	.summary("smartbear-list-projects --organization-id <organization-id> [--raw <json>]")
	.description("List projects in an organization")
	.usage("--organization-id <organization-id> [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.requiredOption("--organization-id <organization-id>", "Bugsnag organization ID (example: example-id)")
	
	.alias("smartbear-list_projects")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.organizationId !== undefined) args.organization_id = cmdOpts.organizationId;
			const call = (proxy.smartbearListProjects as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 60000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call smartbear.smartbear-list_projects(organization_id: \"example-id\")");

program
	.command("smartbear-list-errors")
	.summary("smartbear-list-errors --project-id <project-id> [--status <status:open|fixed|ignored>] [--sort <sort:newest|oldest|priority>] [--limit <limit:number>] [--raw <json>]")
	.description("List errors in a project with filtering options")
	.usage("--project-id <project-id> [--status <status:open|fixed|ignored>] [--sort <sort:newest|oldest|priority>] [--limit <limit:number>] [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.requiredOption("--project-id <project-id>", "Bugsnag project ID (example: example-id)")
	.option("--status <status:open|fixed|ignored>", "Filter by error status (choices: open, fixed, ignored; example: open)")
	.option("--sort <sort:newest|oldest|priority>", "Sort order for errors (choices: newest, oldest, priority; example: newest)")
	.option("--limit <limit:number>", "Maximum number of errors to return (example: 1)", (value) => parseFloat(value))
	
	.alias("smartbear-list_errors")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.projectId !== undefined) args.project_id = cmdOpts.projectId;
		if (cmdOpts.status !== undefined) args.status = cmdOpts.status;
		if (cmdOpts.sort !== undefined) args.sort = cmdOpts.sort;
		if (cmdOpts.limit !== undefined) args.limit = cmdOpts.limit;
			const call = (proxy.smartbearListErrors as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 60000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call smartbear.smartbear-list_errors(project_id: \"example-id\", st, ...)");

program
	.command("smartbear-view-error")
	.summary("smartbear-view-error --error-id <error-id> [--raw <json>]")
	.description("Get detailed information about a specific error")
	.usage("--error-id <error-id> [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.requiredOption("--error-id <error-id>", "Bugsnag error ID (example: example-id)")
	
	.alias("smartbear-view_error")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.errorId !== undefined) args.error_id = cmdOpts.errorId;
			const call = (proxy.smartbearViewError as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 60000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call smartbear.smartbear-view_error(error_id: \"example-id\")");

program
	.command("smartbear-list-error-events")
	.summary("smartbear-list-error-events --project-id <project-id> --error-id <error-id> [--limit <limit:number>] [--raw <json>]")
	.description("List events (occurrences) for a specific error")
	.usage("--project-id <project-id> --error-id <error-id> [--limit <limit:number>] [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.requiredOption("--project-id <project-id>", "Bugsnag project ID (example: example-id)")
	.requiredOption("--error-id <error-id>", "Bugsnag error ID (example: example-id)")
	.option("--limit <limit:number>", "Maximum number of events to return (example: 1)", (value) => parseFloat(value))
	
	.alias("smartbear-list_error_events")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.projectId !== undefined) args.project_id = cmdOpts.projectId;
		if (cmdOpts.errorId !== undefined) args.error_id = cmdOpts.errorId;
		if (cmdOpts.limit !== undefined) args.limit = cmdOpts.limit;
			const call = (proxy.smartbearListErrorEvents as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 60000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call smartbear.smartbear-list_error_events(project_id: \"example-i, ...)");

program
	.command("smartbear-view-latest-event")
	.summary("smartbear-view-latest-event --error-id <error-id> [--raw <json>]")
	.description("View the latest event for an error")
	.usage("--error-id <error-id> [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.requiredOption("--error-id <error-id>", "Bugsnag error ID (example: example-id)")
	
	.alias("smartbear-view_latest_event")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.errorId !== undefined) args.error_id = cmdOpts.errorId;
			const call = (proxy.smartbearViewLatestEvent as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 60000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call smartbear.smartbear-view_latest_event(error_id: \"example-id\")");

program
	.command("smartbear-view-event")
	.summary("smartbear-view-event --project-id <project-id> --event-id <event-id> [--raw <json>]")
	.description("View detailed information about a specific event")
	.usage("--project-id <project-id> --event-id <event-id> [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.requiredOption("--project-id <project-id>", "Bugsnag project ID (example: example-id)")
	.requiredOption("--event-id <event-id>", "Bugsnag event ID (example: example-id)")
	
	.alias("smartbear-view_event")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.projectId !== undefined) args.project_id = cmdOpts.projectId;
		if (cmdOpts.eventId !== undefined) args.event_id = cmdOpts.eventId;
			const call = (proxy.smartbearViewEvent as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 60000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call smartbear.smartbear-view_event(project_id: \"example-id\", eve, ...)");

program
	.command("smartbear-view-stacktrace")
	.summary("smartbear-view-stacktrace --project-id <project-id> --event-id <event-id> [--include-code <include-code:true|false>] [--raw <json>]")
	.description("Extract and format stacktrace information from an event")
	.usage("--project-id <project-id> --event-id <event-id> [--include-code <include-code:true|false>] [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.requiredOption("--project-id <project-id>", "Bugsnag project ID (example: example-id)")
	.requiredOption("--event-id <event-id>", "Bugsnag event ID (example: example-id)")
	.option("--include-code <include-code:true|false>", "Include source code context if available (example: true)", (value) => value !== 'false')
	
	.alias("smartbear-view_stacktrace")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.projectId !== undefined) args.project_id = cmdOpts.projectId;
		if (cmdOpts.eventId !== undefined) args.event_id = cmdOpts.eventId;
		if (cmdOpts.includeCode !== undefined) args.include_code = cmdOpts.includeCode;
			const call = (proxy.smartbearViewStacktrace as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 60000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call smartbear.smartbear-view_stacktrace(project_id: \"example-id\", ...)");

program
	.command("smartbear-view-exception-chain")
	.summary("smartbear-view-exception-chain --project-id <project-id> --event-id <event-id> [--raw <json>]")
	.description("View the full chain of exceptions for an event")
	.usage("--project-id <project-id> --event-id <event-id> [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.requiredOption("--project-id <project-id>", "Bugsnag project ID (example: example-id)")
	.requiredOption("--event-id <event-id>", "Bugsnag event ID (example: example-id)")
	
	.alias("smartbear-view_exception_chain")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.projectId !== undefined) args.project_id = cmdOpts.projectId;
		if (cmdOpts.eventId !== undefined) args.event_id = cmdOpts.eventId;
			const call = (proxy.smartbearViewExceptionChain as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 60000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call smartbear.smartbear-view_exception_chain(project_id: \"exampl, ...)");

program
	.command("smartbear-search-issues")
	.summary("smartbear-search-issues --project-id <project-id> [--query <query>] [--error-class <error-class>] [--app-version <app-version>] [--raw <json>]")
	.description("Search for issues using various criteria")
	.usage("--project-id <project-id> [--query <query>] [--error-class <error-class>] [--app-version <app-version>] [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.requiredOption("--project-id <project-id>", "Bugsnag project ID (example: example-id)")
	.option("--query <query>", "Search query")
	.option("--error-class <error-class>", "Filter by error class")
	.option("--app-version <app-version>", "Filter by app version")
	
	.alias("smartbear-search_issues")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.projectId !== undefined) args.project_id = cmdOpts.projectId;
		if (cmdOpts.query !== undefined) args.query = cmdOpts.query;
		if (cmdOpts.errorClass !== undefined) args.error_class = cmdOpts.errorClass;
		if (cmdOpts.appVersion !== undefined) args.app_version = cmdOpts.appVersion;
			const call = (proxy.smartbearSearchIssues as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 60000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call smartbear.smartbear-search_issues(project_id: \"example-id\")");

program
	.command("smartbear-view-tabs")
	.summary("smartbear-view-tabs --project-id <project-id> --event-id <event-id> [--include-code <include-code:true|false>] [--raw <json>]")
	.description("View all event data tabs including app, device, user, request, breadcrumbs, metadata, and stacktrace")
	.usage("--project-id <project-id> --event-id <event-id> [--include-code <include-code:true|false>] [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.requiredOption("--project-id <project-id>", "Bugsnag project ID (example: example-id)")
	.requiredOption("--event-id <event-id>", "Bugsnag event ID (example: example-id)")
	.option("--include-code <include-code:true|false>", "Include source code context in stacktrace if available (example: true)", (value) => value !== 'false')
	
	.alias("smartbear-view_tabs")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.projectId !== undefined) args.project_id = cmdOpts.projectId;
		if (cmdOpts.eventId !== undefined) args.event_id = cmdOpts.eventId;
		if (cmdOpts.includeCode !== undefined) args.include_code = cmdOpts.includeCode;
			const call = (proxy.smartbearViewTabs as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 60000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call smartbear.smartbear-view_tabs(project_id: \"example-id\", even, ...)");

program
	.command('__mcporter_inspect', { hidden: true })
	.description('Internal metadata printer for mcporter inspect-cli.')
	.action(() => {
		const payload = buildMetadataPayload();
		console.log(JSON.stringify(payload, null, 2));
	});

configureToolCommandHelps();

const FORCE_COLOR = process.env.FORCE_COLOR?.toLowerCase();
const forceDisableColor = FORCE_COLOR === '0' || FORCE_COLOR === 'false';
const forceEnableColor = FORCE_COLOR === '1' || FORCE_COLOR === 'true' || FORCE_COLOR === '2' || FORCE_COLOR === '3';
const hasNoColor = process.env.NO_COLOR !== undefined;
const stdoutStream = process.stdout as NodeJS.WriteStream | undefined;
const supportsAnsiColor = !hasNoColor && (forceEnableColor || (!forceDisableColor && Boolean(stdoutStream?.isTTY)));

const tint = {
	bold(text: string): string {
		return supportsAnsiColor ? '[1m' + text + '[0m' : text;
	},
	dim(text: string): string {
		return supportsAnsiColor ? '[90m' + text + '[0m' : text;
	},
	extraDim(text: string): string {
		return supportsAnsiColor ? '[38;5;244m' + text + '[0m' : text;
	},
};

function configureGeneratedCommandHelp(command: Command): void {
	command.configureHelp({
		commandUsage(target) {
			const usage = (target.name() + ' ' + target.usage()).trim() || target.name();
			return supportsAnsiColor ? tint.bold(usage) : usage;
		},
		optionTerm(option) {
			const term = option.flags ?? '';
			return supportsAnsiColor ? tint.bold(term) : term;
		},
		optionDescription(option) {
			const description = option.description ?? '';
			return supportsAnsiColor ? tint.extraDim(description) : description;
		},
	});
}

function configureToolCommandHelps(): void {
	program.commands.forEach((cmd) => {
		if (cmd.name() === '__mcporter_inspect') {
			return;
		}
		configureGeneratedCommandHelp(cmd);
	});
}

function renderStandaloneHelp(): string {
	const colorfulTitle = tint.bold(embeddedName) + ' ' + tint.dim('— ' + embeddedDescription);
	const plainTitle = embeddedName + ' — ' + embeddedDescription;
	const title = supportsAnsiColor ? colorfulTitle : plainTitle;
	const lines = [title, '', 'Usage: ' + embeddedName + ' <command> [options]', ''];
	if (generatorTools) {
		lines.push(formatEmbeddedTools());
	}
	lines.push('', formatGlobalFlags(), '', formatQuickStart());
	if (generatorInfo) {
		lines.push('', tint.extraDim(generatorInfo));
	}
	return lines.join('\n');
}

program.helpInformation = () => renderStandaloneHelp();

function formatEmbeddedTools(): string {
	const header = supportsAnsiColor ? tint.bold('Embedded tools') : 'Embedded tools';
	if (!generatorTools.length) {
		return header;
	}
	const lines = [header];
	generatorTools.forEach((entry) => {
		const renderedDesc = entry.description
			? supportsAnsiColor
				? tint.extraDim(entry.description)
				: entry.description
			: undefined;
		const base = renderedDesc ? entry.name + ' - ' + renderedDesc : entry.name;
		lines.push('  ' + base);
		if (entry.flags) {
			const renderedFlags = supportsAnsiColor ? tint.extraDim(entry.flags) : entry.flags;
			lines.push('    ' + renderedFlags);
		}
		lines.push('');
	});
	if (lines[lines.length - 1] === '') {
		lines.pop();
	}
	return lines.join('\n');
}

function formatGlobalFlags(): string {
	const header = supportsAnsiColor ? tint.bold('Global flags') : 'Global flags';
	const entries = [
		['-t, --timeout <ms>', 'Call timeout in milliseconds'],
		['-o, --output <format>', 'text | markdown | json | raw (default text)'],
	];
	const formatted = entries.map(([flag, summary]) => '  ' + flag.padEnd(28) + summary);
	return [header, ...formatted].join('\n');
}

function formatQuickStart(): string {
  const header = supportsAnsiColor ? tint.bold('Quick start') : 'Quick start';
  const examples = quickStartExamples();
  if (!examples.length) {
    return header;
  }
  const formatted = examples.map(([cmd, note]) => '  ' + cmd + '\n    ' + tint.dim('# ' + note));
  return [header, ...formatted].join('\n');
}

function quickStartExamples(): Array<[string, string]> {
  const examples: Array<[string, string]> = [];
  const commandMap = new Map<string, string>();
  program.commands.forEach((cmd) => {
    const name = cmd.name();
    if (name !== '__mcporter_inspect') {
      commandMap.set(name, name);
    }
  });
  const embedded = Array.isArray(generatorTools) ? generatorTools : [];
  for (const entry of embedded.slice(0, 3)) {
    const commandName = commandMap.get(entry.name) ?? entry.name;
    const flags = entry.flags ? ' ' + entry.flags.replace(/<[^>]+>/g, '<value>') : '';
    examples.push([embeddedName + ' ' + commandName + flags, 'invoke ' + commandName]);
  }
  if (!examples.length) {
    examples.push([embeddedName + ' <tool> --key value', 'invoke a tool with flags']);
  }
  return examples;
}

function printResult(result: unknown, format: string) {
	const wrapped = createCallResult(result);
	switch (format) {
		case 'json': {
			const json = wrapped.json();
			if (json) {
				console.log(JSON.stringify(json, null, 2));
				return;
			}
			break;
		}
		case 'markdown': {
			const markdown = wrapped.markdown();
			if (markdown) {
				console.log(markdown);
				return;
			}
			break;
		}
		case 'raw': {
			console.log(JSON.stringify(wrapped.raw, null, 2));
			return;
		}
	}
	const text = wrapped.text();
	if (text) {
		console.log(text);
	} else {
		console.log(JSON.stringify(wrapped.raw, null, 2));
	}
}

function normalizeEmbeddedServer(server: typeof embeddedServer) {
	const base = { ...server } as Record<string, unknown>;
	if ((server.command as any).kind === 'http') {
		const urlRaw = (server.command as any).url;
		const urlValue = typeof urlRaw === 'string' ? urlRaw : String(urlRaw);
		return {
			...base,
			command: {
				...(server.command as Record<string, unknown>),
				url: new URL(urlValue),
			},
		};
	}
	if ((server.command as any).kind === 'stdio') {
		return {
			...base,
			command: {
				...(server.command as Record<string, unknown>),
				args: [ ...((server.command as any).args ?? []) ],
			},
		};
	}
	return base;
}

function determineArtifactKind(): 'template' | 'bundle' | 'binary' {
	const scriptPath = typeof process !== 'undefined' && Array.isArray(process.argv) ? process.argv[1] ?? '' : '';
	if (scriptPath.endsWith('.ts')) {
		return 'template';
	}
	if (scriptPath.endsWith('.js')) {
		return 'bundle';
	}
	return 'binary';
}

function resolveArtifactPath(): string {
	if (typeof process !== 'undefined' && Array.isArray(process.argv) && process.argv.length > 1) {
		const script = process.argv[1];
		if (script) {
			return script;
		}
	}
	return embeddedMetadata.artifact.path;
}

function buildMetadataPayload() {
	const invocation = { ...embeddedMetadata.invocation };
	const path = resolveArtifactPath();
	if (artifactKind === 'template' && path) {
		invocation.outputPath = invocation.outputPath ?? path;
	} else if (artifactKind === 'bundle' && path) {
		invocation.bundle = invocation.bundle ?? path;
	} else if (artifactKind === 'binary' && path) {
		invocation.compile = invocation.compile ?? path;
	}
	return {
		...embeddedMetadata,
		artifact: {
			path,
			kind: artifactKind,
		},
		invocation,
	};
}

async function ensureRuntime(): Promise<Awaited<ReturnType<typeof createRuntime>>> {
	return await createRuntime({
		servers: [normalizeEmbeddedServer(embeddedServer)],
	});
}

async function invokeWithTimeout<T>(call: Promise<T>, timeout: number): Promise<T> {
	if (!Number.isFinite(timeout) || timeout <= 0) {
		return await call;
	}
	let timer: ReturnType<typeof setTimeout> | undefined;
	try {
		return await Promise.race([
			call,
			new Promise<never>((_, reject) => {
				timer = setTimeout(() => {
					reject(new Error('Call timed out after ' + timeout + 'ms.'));
				}, timeout);
			}),
		]);
	} finally {
		if (timer) {
			clearTimeout(timer);
		}
	}
}

async function runCli(): Promise<void> {
	const args = process.argv.slice(2);
	if (args.length === 0) {
		program.outputHelp();
		return;
	}
	await program.parseAsync(process.argv);
}

if (process.env.MCPORTER_DISABLE_AUTORUN !== '1') {
	runCli().catch((error) => {
		const message = error instanceof Error ? error.message : String(error);
		console.error(message);
		process.exit(1);
	});
}
