#!/usr/bin/env bun
// @generated by mcporter@0.0.0 on 2026-03-02T20:00:41.227Z. DO NOT EDIT.
import { Command } from 'commander';
import { createRuntime, createServerProxy } from 'mcporter';
import { createCallResult } from 'mcporter';

const embeddedServer = {
  "name": "tavily",
  "description": "mcphub_tavily_group",
  "command": {
    "kind": "http",
    "url": "http://localhost:9700/mcp/tavily",
    "headers": {
      "accept": "application/json, text/event-stream"
    }
  },
  "source": {
    "kind": "import",
    "path": "/home/danil/.claude/mcp.json",
    "importKind": "claude-code"
  },
  "sources": [
    {
      "kind": "import",
      "path": "/home/danil/.claude/mcp.json",
      "importKind": "claude-code"
    }
  ]
} as const;
const embeddedSchemas = {
  "tavily-tavily_search": {
    "type": "object",
    "properties": {
      "query": {
        "type": "string",
        "description": "Search query"
      },
      "search_depth": {
        "type": "string",
        "enum": [
          "basic",
          "advanced",
          "fast",
          "ultra-fast"
        ],
        "description": "The depth of the search. 'basic' for generic results, 'advanced' for more thorough search, 'fast' for optimized low latency with high relevance, 'ultra-fast' for prioritizing latency above all else",
        "default": "basic"
      },
      "topic": {
        "type": "string",
        "enum": [
          "general"
        ],
        "description": "The category of the search. This will determine which of our agents will be used for the search",
        "default": "general"
      },
      "time_range": {
        "type": "string",
        "description": "The time range back from the current date to include in the search results",
        "enum": [
          "day",
          "week",
          "month",
          "year"
        ]
      },
      "start_date": {
        "type": "string",
        "description": "Will return all results after the specified start date. Required to be written in the format YYYY-MM-DD.",
        "default": ""
      },
      "end_date": {
        "type": "string",
        "description": "Will return all results before the specified end date. Required to be written in the format YYYY-MM-DD",
        "default": ""
      },
      "max_results": {
        "type": "number",
        "description": "The maximum number of search results to return",
        "default": 5,
        "minimum": 5,
        "maximum": 20
      },
      "include_images": {
        "type": "boolean",
        "description": "Include a list of query-related images in the response",
        "default": false
      },
      "include_image_descriptions": {
        "type": "boolean",
        "description": "Include a list of query-related images and their descriptions in the response",
        "default": false
      },
      "include_raw_content": {
        "type": "boolean",
        "description": "Include the cleaned and parsed HTML content of each search result",
        "default": false
      },
      "include_domains": {
        "type": "array",
        "items": {
          "type": "string"
        },
        "description": "A list of domains to specifically include in the search results, if the user asks to search on specific sites set this to the domain of the site",
        "default": []
      },
      "exclude_domains": {
        "type": "array",
        "items": {
          "type": "string"
        },
        "description": "List of domains to specifically exclude, if the user asks to exclude a domain set this to the domain of the site",
        "default": []
      },
      "country": {
        "type": "string",
        "description": "Boost search results from a specific country. This will prioritize content from the selected country in the search results. Available only if topic is general.",
        "default": ""
      },
      "include_favicon": {
        "type": "boolean",
        "description": "Whether to include the favicon URL for each result",
        "default": false
      }
    },
    "required": [
      "query"
    ]
  },
  "tavily-tavily_extract": {
    "type": "object",
    "properties": {
      "urls": {
        "type": "array",
        "items": {
          "type": "string"
        },
        "description": "List of URLs to extract content from"
      },
      "extract_depth": {
        "type": "string",
        "enum": [
          "basic",
          "advanced"
        ],
        "description": "Use 'advanced' for LinkedIn, protected sites, or tables/embedded content",
        "default": "basic"
      },
      "include_images": {
        "type": "boolean",
        "description": "Include images from pages",
        "default": false
      },
      "format": {
        "type": "string",
        "enum": [
          "markdown",
          "text"
        ],
        "description": "Output format",
        "default": "markdown"
      },
      "include_favicon": {
        "type": "boolean",
        "description": "Include favicon URLs",
        "default": false
      },
      "query": {
        "type": "string",
        "description": "Query to rerank content chunks by relevance"
      }
    },
    "required": [
      "urls"
    ]
  },
  "tavily-tavily_crawl": {
    "type": "object",
    "properties": {
      "url": {
        "type": "string",
        "description": "The root URL to begin the crawl"
      },
      "max_depth": {
        "type": "integer",
        "description": "Max depth of the crawl. Defines how far from the base URL the crawler can explore.",
        "default": 1,
        "minimum": 1
      },
      "max_breadth": {
        "type": "integer",
        "description": "Max number of links to follow per level of the tree (i.e., per page)",
        "default": 20,
        "minimum": 1
      },
      "limit": {
        "type": "integer",
        "description": "Total number of links the crawler will process before stopping",
        "default": 50,
        "minimum": 1
      },
      "instructions": {
        "type": "string",
        "description": "Natural language instructions for the crawler. Instructions specify which types of pages the crawler should return."
      },
      "select_paths": {
        "type": "array",
        "items": {
          "type": "string"
        },
        "description": "Regex patterns to select only URLs with specific path patterns (e.g., /docs/.*, /api/v1.*)",
        "default": []
      },
      "select_domains": {
        "type": "array",
        "items": {
          "type": "string"
        },
        "description": "Regex patterns to restrict crawling to specific domains or subdomains (e.g., ^docs\\.example\\.com$)",
        "default": []
      },
      "allow_external": {
        "type": "boolean",
        "description": "Whether to return external links in the final response",
        "default": true
      },
      "extract_depth": {
        "type": "string",
        "enum": [
          "basic",
          "advanced"
        ],
        "description": "Advanced extraction retrieves more data, including tables and embedded content, with higher success but may increase latency",
        "default": "basic"
      },
      "format": {
        "type": "string",
        "enum": [
          "markdown",
          "text"
        ],
        "description": "The format of the extracted web page content. markdown returns content in markdown format. text returns plain text and may increase latency.",
        "default": "markdown"
      },
      "include_favicon": {
        "type": "boolean",
        "description": "Whether to include the favicon URL for each result",
        "default": false
      }
    },
    "required": [
      "url"
    ]
  },
  "tavily-tavily_map": {
    "type": "object",
    "properties": {
      "url": {
        "type": "string",
        "description": "The root URL to begin the mapping"
      },
      "max_depth": {
        "type": "integer",
        "description": "Max depth of the mapping. Defines how far from the base URL the crawler can explore",
        "default": 1,
        "minimum": 1
      },
      "max_breadth": {
        "type": "integer",
        "description": "Max number of links to follow per level of the tree (i.e., per page)",
        "default": 20,
        "minimum": 1
      },
      "limit": {
        "type": "integer",
        "description": "Total number of links the crawler will process before stopping",
        "default": 50,
        "minimum": 1
      },
      "instructions": {
        "type": "string",
        "description": "Natural language instructions for the crawler"
      },
      "select_paths": {
        "type": "array",
        "items": {
          "type": "string"
        },
        "description": "Regex patterns to select only URLs with specific path patterns (e.g., /docs/.*, /api/v1.*)",
        "default": []
      },
      "select_domains": {
        "type": "array",
        "items": {
          "type": "string"
        },
        "description": "Regex patterns to restrict crawling to specific domains or subdomains (e.g., ^docs\\.example\\.com$)",
        "default": []
      },
      "allow_external": {
        "type": "boolean",
        "description": "Whether to return external links in the final response",
        "default": true
      }
    },
    "required": [
      "url"
    ]
  },
  "tavily-tavily_research": {
    "type": "object",
    "properties": {
      "input": {
        "type": "string",
        "description": "A comprehensive description of the research task"
      },
      "model": {
        "type": "string",
        "enum": [
          "mini",
          "pro",
          "auto"
        ],
        "description": "Defines the degree of depth of the research. 'mini' is good for narrow tasks with few subtopics. 'pro' is good for broad tasks with many subtopics. 'auto' automatically selects the best model.",
        "default": "auto"
      }
    },
    "required": [
      "input"
    ]
  }
} as const;
const embeddedName = "tavily";
const embeddedDescription = "mcphub_tavily_group";
const generatorInfo = "Generated by mcporter@0.0.0 — https://github.com/steipete/mcporter";
const generatorTools = [
  {
    "name": "tavily-tavily-search",
    "description": "Search the web for current information on any topic. Use for news, facts, or data beyond your knowledge cutoff. Returns snippets and source URLs.",
    "usage": "tavily-tavily-search --query <query> [--search-depth <search-depth:basic|advanced|fast|ultra-fast>] [--topic <topic:general>] [--time-range <time-range:day|week|month|year>] [--start-date <start-date>] [--raw <json>]",
    "flags": "--query <query> [--search-depth <search-depth:basic|advanced|fast|ultra-fast>] [--topic <topic:general>] [--time-range <time-range:day|week|month|year>] [--start-date <start-date>] [--raw <json>]"
  },
  {
    "name": "tavily-tavily-extract",
    "description": "Extract content from URLs. Returns raw page content in markdown or text format.",
    "usage": "tavily-tavily-extract --urls <urls:value1,value2> [--extract-depth <extract-depth:basic|advanced>] [--include-images <include-images:true|false>] [--format <format:markdown|text>] [--include-favicon <include-favicon:true|false>] [--raw <json>]",
    "flags": "--urls <urls:value1,value2> [--extract-depth <extract-depth:basic|advanced>] [--include-images <include-images:true|false>] [--format <format:markdown|text>] [--include-favicon <include-favicon:true|false>] [--raw <json>]"
  },
  {
    "name": "tavily-tavily-crawl",
    "description": "Crawl a website starting from a URL. Extracts content from pages with configurable depth and breadth.",
    "usage": "tavily-tavily-crawl --url <url> [--max-depth <max-depth:number>] [--max-breadth <max-breadth:number>] [--limit <limit:number>] [--instructions <instructions>] [--raw <json>]",
    "flags": "--url <url> [--max-depth <max-depth:number>] [--max-breadth <max-breadth:number>] [--limit <limit:number>] [--instructions <instructions>] [--raw <json>]"
  },
  {
    "name": "tavily-tavily-map",
    "description": "Map a website's structure. Returns a list of URLs found starting from the base URL.",
    "usage": "tavily-tavily-map --url <url> [--max-depth <max-depth:number>] [--max-breadth <max-breadth:number>] [--limit <limit:number>] [--instructions <instructions>] [--raw <json>]",
    "flags": "--url <url> [--max-depth <max-depth:number>] [--max-breadth <max-breadth:number>] [--limit <limit:number>] [--instructions <instructions>] [--raw <json>]"
  },
  {
    "name": "tavily-tavily-research",
    "description": "Perform comprehensive research on a given topic or question. Use this tool when you need to gather information from multiple sources to answer a question or complete a task. Returns a detailed response based on the research findings.",
    "usage": "tavily-tavily-research --input <input> [--model <model:mini|pro|auto>] [--raw <json>]",
    "flags": "--input <input> [--model <model:mini|pro|auto>] [--raw <json>]"
  }
] as const;
const embeddedMetadata = {
  "schemaVersion": 1,
  "generatedAt": "2026-03-02T20:00:41.227Z",
  "generator": {
    "name": "mcporter",
    "version": "0.0.0"
  },
  "server": {
    "name": "tavily",
    "source": {
      "kind": "import",
      "path": "/home/danil/.claude/mcp.json",
      "importKind": "claude-code"
    },
    "definition": {
      "name": "tavily",
      "description": "mcphub_tavily_group",
      "command": {
        "kind": "http",
        "url": "http://localhost:9700/mcp/tavily",
        "headers": {
          "accept": "application/json, text/event-stream"
        }
      }
    }
  },
  "artifact": {
    "path": "",
    "kind": "template"
  },
  "invocation": {
    "serverRef": "tavily",
    "runtime": "bun",
    "bundler": "bun",
    "timeoutMs": 60000,
    "minify": false
  }
} as const;
const artifactKind = determineArtifactKind();
const program = new Command();
program.name(embeddedName);
program.description(embeddedDescription);
program.option('-t, --timeout <ms>', 'Call timeout in milliseconds', (value) => parseInt(value, 10), 60000);
program.option('-o, --output <format>', 'Output format: text|markdown|json|raw', 'text');
const commandSignatures: Record<string, string> = {
  "tavily-tavily-search": "function tavily-tavily_search(query: string, search_depth?: \"basic\" | \"advanced\" | \"fast\" | \"ultra-fast\", topic?: \"general\", time_range?: \"day\" | \"week\" | \"month\" | \"year\", start_date?: string);",
  "tavily-tavily-extract": "function tavily-tavily_extract(urls: string[], extract_depth?: \"basic\" | \"advanced\", include_images?: boolean, format?: \"markdown\" | \"text\", include_favicon?: boolean);",
  "tavily-tavily-crawl": "function tavily-tavily_crawl(url: string, max_depth?: number, max_breadth?: number, limit?: number, instructions?: string);",
  "tavily-tavily-map": "function tavily-tavily_map(url: string, max_depth?: number, max_breadth?: number, limit?: number, instructions?: string);",
  "tavily-tavily-research": "function tavily-tavily_research(input: string, model?: \"mini\" | \"pro\" | \"auto\");"
};
program.configureHelp({
	commandTerm(cmd) {
		const term = cmd.name();
		return commandSignatures[term] ?? cmd.name();
	},
});
program.showSuggestionAfterError(true);

program
	.command("tavily-tavily-search")
	.summary("tavily-tavily-search --query <query> [--search-depth <search-depth:basic|advanced|fast|ultra-fast>] [--topic <topic:general>] [--time-range <time-range:day|week|month|year>] [--start-date <start-date>] [--raw <json>]")
	.description("Search the web for current information on any topic. Use for news, facts, or data beyond your knowledge cutoff. Returns snippets and source URLs.")
	.usage("--query <query> [--search-depth <search-depth:basic|advanced|fast|ultra-fast>] [--topic <topic:general>] [--time-range <time-range:day|week|month|year>] [--start-date <start-date>] [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.requiredOption("--query <query>", "Search query")
	.option("--search-depth <search-depth:basic|advanced|fast|ultra-fast>", "The depth of the search. 'basic' for generic results, 'advanced' for more thorough search, 'fast' for optimized low latency with high relevance, 'ultra-fast' for prioritizing latency above all else (choices: basic, advanced, fast, ultra-fast; default: basic; example: basic)")
	.option("--topic <topic:general>", "The category of the search. This will determine which of our agents will be used for the search (choices: general; default: general; example: general)")
	.option("--time-range <time-range:day|week|month|year>", "The time range back from the current date to include in the search results (choices: day, week, month, year; example: day)")
	.option("--start-date <start-date>", "Will return all results after the specified start date. Required to be written in the format YYYY-MM-DD. (default: )")
	.option("--end-date <end-date>", "Will return all results before the specified end date. Required to be written in the format YYYY-MM-DD (default: )")
	.option("--max-results <max-results:number>", "The maximum number of search results to return (default: 5; example: 5)", (value) => parseFloat(value))
	.option("--include-images <include-images:true|false>", "Include a list of query-related images in the response (default: false; example: false)", (value) => value !== 'false')
	.option("--include-image-descriptions <include-image-descriptions:true|false>", "Include a list of query-related images and their descriptions in the response (default: false; example: false)", (value) => value !== 'false')
	.option("--include-raw-content <include-raw-content:true|false>", "Include the cleaned and parsed HTML content of each search result (default: false; example: false)", (value) => value !== 'false')
	.option("--include-domains <include-domains:value1,value2>", "A list of domains to specifically include in the search results, if the user asks to search on specific sites set this to the domain of the site (default: ; example: [])", (value) => value.split(',').map((v) => v.trim()))
	.option("--exclude-domains <exclude-domains:value1,value2>", "List of domains to specifically exclude, if the user asks to exclude a domain set this to the domain of the site (default: ; example: [])", (value) => value.split(',').map((v) => v.trim()))
	.option("--country <country>", "Boost search results from a specific country. This will prioritize content from the selected country in the search results. Available only if topic is general. (default: )")
	.option("--include-favicon <include-favicon:true|false>", "Whether to include the favicon URL for each result (default: false; example: false)", (value) => value !== 'false')
	
	.alias("tavily-tavily_search")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.query !== undefined) args.query = cmdOpts.query;
		if (cmdOpts.searchDepth !== undefined) args.search_depth = cmdOpts.searchDepth;
		if (cmdOpts.topic !== undefined) args.topic = cmdOpts.topic;
		if (cmdOpts.timeRange !== undefined) args.time_range = cmdOpts.timeRange;
		if (cmdOpts.startDate !== undefined) args.start_date = cmdOpts.startDate;
		if (cmdOpts.endDate !== undefined) args.end_date = cmdOpts.endDate;
		if (cmdOpts.maxResults !== undefined) args.max_results = cmdOpts.maxResults;
		if (cmdOpts.includeImages !== undefined) args.include_images = cmdOpts.includeImages;
		if (cmdOpts.includeImageDescriptions !== undefined) args.include_image_descriptions = cmdOpts.includeImageDescriptions;
		if (cmdOpts.includeRawContent !== undefined) args.include_raw_content = cmdOpts.includeRawContent;
		if (cmdOpts.includeDomains !== undefined) args.include_domains = cmdOpts.includeDomains;
		if (cmdOpts.excludeDomains !== undefined) args.exclude_domains = cmdOpts.excludeDomains;
		if (cmdOpts.country !== undefined) args.country = cmdOpts.country;
		if (cmdOpts.includeFavicon !== undefined) args.include_favicon = cmdOpts.includeFavicon;
			const call = (proxy.tavilyTavilySearch as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 60000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call tavily.tavily-tavily_search(query: \"value\", search_depth: \"b, ...)")
	.addHelpText('afterAll', () => '\n' + "// optional (9): end_date, max_results, include_images, include_image_descriptions, include_raw_content, ..." + '\n');

program
	.command("tavily-tavily-extract")
	.summary("tavily-tavily-extract --urls <urls:value1,value2> [--extract-depth <extract-depth:basic|advanced>] [--include-images <include-images:true|false>] [--format <format:markdown|text>] [--include-favicon <include-favicon:true|false>] [--raw <json>]")
	.description("Extract content from URLs. Returns raw page content in markdown or text format.")
	.usage("--urls <urls:value1,value2> [--extract-depth <extract-depth:basic|advanced>] [--include-images <include-images:true|false>] [--format <format:markdown|text>] [--include-favicon <include-favicon:true|false>] [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.requiredOption("--urls <urls:value1,value2>", "List of URLs to extract content from (example: value1,value2)", (value) => value.split(',').map((v) => v.trim()))
	.option("--extract-depth <extract-depth:basic|advanced>", "Use 'advanced' for LinkedIn, protected sites, or tables/embedded content (choices: basic, advanced; default: basic; example: basic)")
	.option("--include-images <include-images:true|false>", "Include images from pages (default: false; example: false)", (value) => value !== 'false')
	.option("--format <format:markdown|text>", "Output format (choices: markdown, text; default: markdown; example: markdown)")
	.option("--include-favicon <include-favicon:true|false>", "Include favicon URLs (default: false; example: false)", (value) => value !== 'false')
	.option("--query <query>", "Query to rerank content chunks by relevance")
	
	.alias("tavily-tavily_extract")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.urls !== undefined) args.urls = cmdOpts.urls;
		if (cmdOpts.extractDepth !== undefined) args.extract_depth = cmdOpts.extractDepth;
		if (cmdOpts.includeImages !== undefined) args.include_images = cmdOpts.includeImages;
		if (cmdOpts.format !== undefined) args.format = cmdOpts.format;
		if (cmdOpts.includeFavicon !== undefined) args.include_favicon = cmdOpts.includeFavicon;
		if (cmdOpts.query !== undefined) args.query = cmdOpts.query;
			const call = (proxy.tavilyTavilyExtract as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 60000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call tavily.tavily-tavily_extract(urls: [\"value1\", \"value2\"], ext, ...)")
	.addHelpText('afterAll', () => '\n' + "// optional (1): query" + '\n');

program
	.command("tavily-tavily-crawl")
	.summary("tavily-tavily-crawl --url <url> [--max-depth <max-depth:number>] [--max-breadth <max-breadth:number>] [--limit <limit:number>] [--instructions <instructions>] [--raw <json>]")
	.description("Crawl a website starting from a URL. Extracts content from pages with configurable depth and breadth.")
	.usage("--url <url> [--max-depth <max-depth:number>] [--max-breadth <max-breadth:number>] [--limit <limit:number>] [--instructions <instructions>] [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.requiredOption("--url <url>", "The root URL to begin the crawl")
	.option("--max-depth <max-depth:number>", "Max depth of the crawl. Defines how far from the base URL the crawler can explore. (default: 1; example: 1)", (value) => parseFloat(value))
	.option("--max-breadth <max-breadth:number>", "Max number of links to follow per level of the tree (i.e., per page) (default: 20; example: 20)", (value) => parseFloat(value))
	.option("--limit <limit:number>", "Total number of links the crawler will process before stopping (default: 50; example: 50)", (value) => parseFloat(value))
	.option("--instructions <instructions>", "Natural language instructions for the crawler. Instructions specify which types of pages the crawler should return.")
	.option("--select-paths <select-paths:value1,value2>", "Regex patterns to select only URLs with specific path patterns (e.g., /docs/.*, /api/v1.*) (default: ; example: [])", (value) => value.split(',').map((v) => v.trim()))
	.option("--select-domains <select-domains:value1,value2>", "Regex patterns to restrict crawling to specific domains or subdomains (e.g., ^docs\\.example\\.com$) (default: ; example: [])", (value) => value.split(',').map((v) => v.trim()))
	.option("--allow-external <allow-external:true|false>", "Whether to return external links in the final response (default: true; example: true)", (value) => value !== 'false')
	.option("--extract-depth <extract-depth:basic|advanced>", "Advanced extraction retrieves more data, including tables and embedded content, with higher success but may increase latency (choices: basic, advanced; default: basic; example: basic)")
	.option("--format <format:markdown|text>", "The format of the extracted web page content. markdown returns content in markdown format. text returns plain text and may increase latency. (choices: markdown, text; default: markdown; example: markdown)")
	.option("--include-favicon <include-favicon:true|false>", "Whether to include the favicon URL for each result (default: false; example: false)", (value) => value !== 'false')
	
	.alias("tavily-tavily_crawl")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.url !== undefined) args.url = cmdOpts.url;
		if (cmdOpts.maxDepth !== undefined) args.max_depth = cmdOpts.maxDepth;
		if (cmdOpts.maxBreadth !== undefined) args.max_breadth = cmdOpts.maxBreadth;
		if (cmdOpts.limit !== undefined) args.limit = cmdOpts.limit;
		if (cmdOpts.instructions !== undefined) args.instructions = cmdOpts.instructions;
		if (cmdOpts.selectPaths !== undefined) args.select_paths = cmdOpts.selectPaths;
		if (cmdOpts.selectDomains !== undefined) args.select_domains = cmdOpts.selectDomains;
		if (cmdOpts.allowExternal !== undefined) args.allow_external = cmdOpts.allowExternal;
		if (cmdOpts.extractDepth !== undefined) args.extract_depth = cmdOpts.extractDepth;
		if (cmdOpts.format !== undefined) args.format = cmdOpts.format;
		if (cmdOpts.includeFavicon !== undefined) args.include_favicon = cmdOpts.includeFavicon;
			const call = (proxy.tavilyTavilyCrawl as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 60000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call tavily.tavily-tavily_crawl(url: \"https://example.com\", max_d, ...)")
	.addHelpText('afterAll', () => '\n' + "// optional (6): select_paths, select_domains, allow_external, extract_depth, format, ..." + '\n');

program
	.command("tavily-tavily-map")
	.summary("tavily-tavily-map --url <url> [--max-depth <max-depth:number>] [--max-breadth <max-breadth:number>] [--limit <limit:number>] [--instructions <instructions>] [--raw <json>]")
	.description("Map a website's structure. Returns a list of URLs found starting from the base URL.")
	.usage("--url <url> [--max-depth <max-depth:number>] [--max-breadth <max-breadth:number>] [--limit <limit:number>] [--instructions <instructions>] [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.requiredOption("--url <url>", "The root URL to begin the mapping")
	.option("--max-depth <max-depth:number>", "Max depth of the mapping. Defines how far from the base URL the crawler can explore (default: 1; example: 1)", (value) => parseFloat(value))
	.option("--max-breadth <max-breadth:number>", "Max number of links to follow per level of the tree (i.e., per page) (default: 20; example: 20)", (value) => parseFloat(value))
	.option("--limit <limit:number>", "Total number of links the crawler will process before stopping (default: 50; example: 50)", (value) => parseFloat(value))
	.option("--instructions <instructions>", "Natural language instructions for the crawler")
	.option("--select-paths <select-paths:value1,value2>", "Regex patterns to select only URLs with specific path patterns (e.g., /docs/.*, /api/v1.*) (default: ; example: [])", (value) => value.split(',').map((v) => v.trim()))
	.option("--select-domains <select-domains:value1,value2>", "Regex patterns to restrict crawling to specific domains or subdomains (e.g., ^docs\\.example\\.com$) (default: ; example: [])", (value) => value.split(',').map((v) => v.trim()))
	.option("--allow-external <allow-external:true|false>", "Whether to return external links in the final response (default: true; example: true)", (value) => value !== 'false')
	
	.alias("tavily-tavily_map")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.url !== undefined) args.url = cmdOpts.url;
		if (cmdOpts.maxDepth !== undefined) args.max_depth = cmdOpts.maxDepth;
		if (cmdOpts.maxBreadth !== undefined) args.max_breadth = cmdOpts.maxBreadth;
		if (cmdOpts.limit !== undefined) args.limit = cmdOpts.limit;
		if (cmdOpts.instructions !== undefined) args.instructions = cmdOpts.instructions;
		if (cmdOpts.selectPaths !== undefined) args.select_paths = cmdOpts.selectPaths;
		if (cmdOpts.selectDomains !== undefined) args.select_domains = cmdOpts.selectDomains;
		if (cmdOpts.allowExternal !== undefined) args.allow_external = cmdOpts.allowExternal;
			const call = (proxy.tavilyTavilyMap as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 60000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call tavily.tavily-tavily_map(url: \"https://example.com\", max_dep, ...)")
	.addHelpText('afterAll', () => '\n' + "// optional (3): select_paths, select_domains, allow_external" + '\n');

program
	.command("tavily-tavily-research")
	.summary("tavily-tavily-research --input <input> [--model <model:mini|pro|auto>] [--raw <json>]")
	.description("Perform comprehensive research on a given topic or question. Use this tool when you need to gather information from multiple sources to answer a question or complete a task. Returns a detailed response based on the research findings.")
	.usage("--input <input> [--model <model:mini|pro|auto>] [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.requiredOption("--input <input>", "A comprehensive description of the research task")
	.option("--model <model:mini|pro|auto>", "Defines the degree of depth of the research. 'mini' is good for narrow tasks with few subtopics. 'pro' is good for broad tasks with many subtopics. 'auto' automatically selects the best model. (choices: mini, pro, auto; default: auto; example: mini)")
	
	.alias("tavily-tavily_research")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.input !== undefined) args.input = cmdOpts.input;
		if (cmdOpts.model !== undefined) args.model = cmdOpts.model;
			const call = (proxy.tavilyTavilyResearch as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 60000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call tavily.tavily-tavily_research(input: \"value\", model: \"mini\")");

program
	.command('__mcporter_inspect', { hidden: true })
	.description('Internal metadata printer for mcporter inspect-cli.')
	.action(() => {
		const payload = buildMetadataPayload();
		console.log(JSON.stringify(payload, null, 2));
	});

configureToolCommandHelps();

const FORCE_COLOR = process.env.FORCE_COLOR?.toLowerCase();
const forceDisableColor = FORCE_COLOR === '0' || FORCE_COLOR === 'false';
const forceEnableColor = FORCE_COLOR === '1' || FORCE_COLOR === 'true' || FORCE_COLOR === '2' || FORCE_COLOR === '3';
const hasNoColor = process.env.NO_COLOR !== undefined;
const stdoutStream = process.stdout as NodeJS.WriteStream | undefined;
const supportsAnsiColor = !hasNoColor && (forceEnableColor || (!forceDisableColor && Boolean(stdoutStream?.isTTY)));

const tint = {
	bold(text: string): string {
		return supportsAnsiColor ? '[1m' + text + '[0m' : text;
	},
	dim(text: string): string {
		return supportsAnsiColor ? '[90m' + text + '[0m' : text;
	},
	extraDim(text: string): string {
		return supportsAnsiColor ? '[38;5;244m' + text + '[0m' : text;
	},
};

function configureGeneratedCommandHelp(command: Command): void {
	command.configureHelp({
		commandUsage(target) {
			const usage = (target.name() + ' ' + target.usage()).trim() || target.name();
			return supportsAnsiColor ? tint.bold(usage) : usage;
		},
		optionTerm(option) {
			const term = option.flags ?? '';
			return supportsAnsiColor ? tint.bold(term) : term;
		},
		optionDescription(option) {
			const description = option.description ?? '';
			return supportsAnsiColor ? tint.extraDim(description) : description;
		},
	});
}

function configureToolCommandHelps(): void {
	program.commands.forEach((cmd) => {
		if (cmd.name() === '__mcporter_inspect') {
			return;
		}
		configureGeneratedCommandHelp(cmd);
	});
}

function renderStandaloneHelp(): string {
	const colorfulTitle = tint.bold(embeddedName) + ' ' + tint.dim('— ' + embeddedDescription);
	const plainTitle = embeddedName + ' — ' + embeddedDescription;
	const title = supportsAnsiColor ? colorfulTitle : plainTitle;
	const lines = [title, '', 'Usage: ' + embeddedName + ' <command> [options]', ''];
	if (generatorTools) {
		lines.push(formatEmbeddedTools());
	}
	lines.push('', formatGlobalFlags(), '', formatQuickStart());
	if (generatorInfo) {
		lines.push('', tint.extraDim(generatorInfo));
	}
	return lines.join('\n');
}

program.helpInformation = () => renderStandaloneHelp();

function formatEmbeddedTools(): string {
	const header = supportsAnsiColor ? tint.bold('Embedded tools') : 'Embedded tools';
	if (!generatorTools.length) {
		return header;
	}
	const lines = [header];
	generatorTools.forEach((entry) => {
		const renderedDesc = entry.description
			? supportsAnsiColor
				? tint.extraDim(entry.description)
				: entry.description
			: undefined;
		const base = renderedDesc ? entry.name + ' - ' + renderedDesc : entry.name;
		lines.push('  ' + base);
		if (entry.flags) {
			const renderedFlags = supportsAnsiColor ? tint.extraDim(entry.flags) : entry.flags;
			lines.push('    ' + renderedFlags);
		}
		lines.push('');
	});
	if (lines[lines.length - 1] === '') {
		lines.pop();
	}
	return lines.join('\n');
}

function formatGlobalFlags(): string {
	const header = supportsAnsiColor ? tint.bold('Global flags') : 'Global flags';
	const entries = [
		['-t, --timeout <ms>', 'Call timeout in milliseconds'],
		['-o, --output <format>', 'text | markdown | json | raw (default text)'],
	];
	const formatted = entries.map(([flag, summary]) => '  ' + flag.padEnd(28) + summary);
	return [header, ...formatted].join('\n');
}

function formatQuickStart(): string {
  const header = supportsAnsiColor ? tint.bold('Quick start') : 'Quick start';
  const examples = quickStartExamples();
  if (!examples.length) {
    return header;
  }
  const formatted = examples.map(([cmd, note]) => '  ' + cmd + '\n    ' + tint.dim('# ' + note));
  return [header, ...formatted].join('\n');
}

function quickStartExamples(): Array<[string, string]> {
  const examples: Array<[string, string]> = [];
  const commandMap = new Map<string, string>();
  program.commands.forEach((cmd) => {
    const name = cmd.name();
    if (name !== '__mcporter_inspect') {
      commandMap.set(name, name);
    }
  });
  const embedded = Array.isArray(generatorTools) ? generatorTools : [];
  for (const entry of embedded.slice(0, 3)) {
    const commandName = commandMap.get(entry.name) ?? entry.name;
    const flags = entry.flags ? ' ' + entry.flags.replace(/<[^>]+>/g, '<value>') : '';
    examples.push([embeddedName + ' ' + commandName + flags, 'invoke ' + commandName]);
  }
  if (!examples.length) {
    examples.push([embeddedName + ' <tool> --key value', 'invoke a tool with flags']);
  }
  return examples;
}

function printResult(result: unknown, format: string) {
	const wrapped = createCallResult(result);
	switch (format) {
		case 'json': {
			const json = wrapped.json();
			if (json) {
				console.log(JSON.stringify(json, null, 2));
				return;
			}
			break;
		}
		case 'markdown': {
			const markdown = wrapped.markdown();
			if (markdown) {
				console.log(markdown);
				return;
			}
			break;
		}
		case 'raw': {
			console.log(JSON.stringify(wrapped.raw, null, 2));
			return;
		}
	}
	const text = wrapped.text();
	if (text) {
		console.log(text);
	} else {
		console.log(JSON.stringify(wrapped.raw, null, 2));
	}
}

function normalizeEmbeddedServer(server: typeof embeddedServer) {
	const base = { ...server } as Record<string, unknown>;
	if ((server.command as any).kind === 'http') {
		const urlRaw = (server.command as any).url;
		const urlValue = typeof urlRaw === 'string' ? urlRaw : String(urlRaw);
		return {
			...base,
			command: {
				...(server.command as Record<string, unknown>),
				url: new URL(urlValue),
			},
		};
	}
	if ((server.command as any).kind === 'stdio') {
		return {
			...base,
			command: {
				...(server.command as Record<string, unknown>),
				args: [ ...((server.command as any).args ?? []) ],
			},
		};
	}
	return base;
}

function determineArtifactKind(): 'template' | 'bundle' | 'binary' {
	const scriptPath = typeof process !== 'undefined' && Array.isArray(process.argv) ? process.argv[1] ?? '' : '';
	if (scriptPath.endsWith('.ts')) {
		return 'template';
	}
	if (scriptPath.endsWith('.js')) {
		return 'bundle';
	}
	return 'binary';
}

function resolveArtifactPath(): string {
	if (typeof process !== 'undefined' && Array.isArray(process.argv) && process.argv.length > 1) {
		const script = process.argv[1];
		if (script) {
			return script;
		}
	}
	return embeddedMetadata.artifact.path;
}

function buildMetadataPayload() {
	const invocation = { ...embeddedMetadata.invocation };
	const path = resolveArtifactPath();
	if (artifactKind === 'template' && path) {
		invocation.outputPath = invocation.outputPath ?? path;
	} else if (artifactKind === 'bundle' && path) {
		invocation.bundle = invocation.bundle ?? path;
	} else if (artifactKind === 'binary' && path) {
		invocation.compile = invocation.compile ?? path;
	}
	return {
		...embeddedMetadata,
		artifact: {
			path,
			kind: artifactKind,
		},
		invocation,
	};
}

async function ensureRuntime(): Promise<Awaited<ReturnType<typeof createRuntime>>> {
	return await createRuntime({
		servers: [normalizeEmbeddedServer(embeddedServer)],
	});
}

async function invokeWithTimeout<T>(call: Promise<T>, timeout: number): Promise<T> {
	if (!Number.isFinite(timeout) || timeout <= 0) {
		return await call;
	}
	let timer: ReturnType<typeof setTimeout> | undefined;
	try {
		return await Promise.race([
			call,
			new Promise<never>((_, reject) => {
				timer = setTimeout(() => {
					reject(new Error('Call timed out after ' + timeout + 'ms.'));
				}, timeout);
			}),
		]);
	} finally {
		if (timer) {
			clearTimeout(timer);
		}
	}
}

async function runCli(): Promise<void> {
	const args = process.argv.slice(2);
	if (args.length === 0) {
		program.outputHelp();
		return;
	}
	await program.parseAsync(process.argv);
}

if (process.env.MCPORTER_DISABLE_AUTORUN !== '1') {
	runCli().catch((error) => {
		const message = error instanceof Error ? error.message : String(error);
		console.error(message);
		process.exit(1);
	});
}
